### ISSUE TITLE
Setup SAST

### ISSUE THREAD

**Issue by leordev** [TBD54566975/web5-kt#121]
We need to set up static analysis / linting (most likely with CodeQL) for this repository.

**Comment by andresuribe87** [comment]
We already do this with https://detekt.dev/. Did you have something additional in mind?

See https://github.com/TBD54566975/web5-kt/commit/25ea1944fd46f98a6b146eb3eae4d281c6d546bf

**Comment by leordev** [comment]
Awesome! 

- Is the detekt analysis being run in the pipeline or only locally?
- Do you know if it runs security checks to detect vulnerabilities in code? (eg.: SQL injection entry points) 
  - Snyk CLI does https://docs.snyk.io/snyk-cli/commands/code-test
  - I did a quick run locally for web5-kt and it didn't find anything! 🎉

**Comment by andresuribe87** [comment]
Detekt is run both locally and in CI. When the task `build` is run, it also runs detekt. 

Not sure about security vulnerability. Will need to check the docs

**Comment by leordev** [comment]
Oh, and last thing we want in the SAST is to report the SARIF to GH Code Scanning tab. It seems detekt can generate a SARIF file from what I saw [here](https://slack-chats.kotlinlang.org/t/502574/i-am-trying-codeql-action-detekt-i-can-upload-the-sarif-file): 

```yml
- name: Upload code analysis reports
  uses: github/codeql-action/upload-sarif@v1
  with:
    sarif_file: build/reports/detekt/detekt.sarif
```
